### PR TITLE
Testing/cypress testing

### PR DESCRIPTION
**Pull request by mr-ryan12**
## Checklist
- [x] Tests written where required
- [x] All tests passing
- [x] Unused code/prys/etc deleted
Testing Coverage at <percentage>%

## Changes Made
  
What (if any) features are you implementing?
- Added Cypress testing for all user flows
- Stubbed intercepts for network requests
- Included fixture files to mock responses
- Used `git rebase` workflow

What (if anything) did you refactor?
- Refactored test suites for readability and testing flows

Were there any issues that arose?
- Need to include additional sad path testing after we implement error handling functionality

Is there anything that you need from your teammate?
- PR reviews, comments and mentor/PM input

Any other comments, questions, or concerns?
- All tests passing as intended. We still need to test for the favoriting functionality, which is being built currently. Additional sad path testing will be included once error handling functionality is implemented.
- Still need to remove `test_spec.js` since it was only used to initialize our continuous integration
- All tests passing locally and on CircleCI
Screen Shot 2022-04-03 at 4 02 35 PM

### CODE REVIEW

**Review by CJSpohn — APPROVED** [review]
Overall thoughts are this is solid work and things are looking good! You all should be feeling super proud of this work! 

I have a few things for the sake of feedback but don't take these as gospel. Normally I would leave comments directly in the code here but because I didn't see anything that required immediate attention I figured considering the stress of late stage Turing and the time constraints you all face I would rather dump some general thoughts here for you to read on your own time so you don't feel compelled to hold this PR up making changes that don't matter _that_ much. 

### Size
This PR is on the bigger side. Sometimes it's inevitable that changes you make require touching several files. I would argue that isn't the case here. In the scope of Turing projects there's ultimately nothing wrong with the size of this PR, but that is something that is treated with a lot more diligence in the working world. Changes should be small, traceable, and very contained because when problems arise it's important to be able to trace back exactly what, where, and why things went wrong for speedy recovery. 

A good rule of thumb is single digit files changed. When you're reviewing PRs in the wild it's important to consider developer empathy and the time commitment required for someone to get in there and review all the changes. I think adding functionality, fixtures, and the bulk of the tests could have been different PRs. 

You will (hopefully) never code on the job at the same pace that you code at Turing so you are able to do things a little bit more diligently.

### Testing
I see a lot of `.wait()` in the Cypress code. Generally most FE testing libraries have a default timeout for methods that search the DOM such as `.get()` in Cypress. I believe `.get()` has a default timeout of a few seconds. You can usually override this in optional parameters for specific cases but _generally_ seeing waits like this is sort of a red flag and usually causes some extra scrutiny. 

Most of the time if something is taking an exceptionally long time to happen on the DOM it's a symptom of a bigger issue, especially if you're stubbing requests. Not something you need to change or refactor here, just something I wanted to point out.

### DOM manipulation
I saw some direct DOM manipulation in `SubmissionForm`. If this was a PR at my job this is definitely something I would ask to be refactored in favor of the `useRef` hook. Essentially it allows you to attach to a specific DOM node the same way `querySelector` does but there are a few advantages.

Direct DOM manipulation within a framework like React is a bit anti-pattern. By using `useRef` you gain a few advantages:
* it is less fallible as you don't have to scan the DOM for classnames or elements
* it is aware of the lifecycle methods of React and you can reap those benefits as components mount/unmount etc
* The code would not break when a DOM is not present but elements still require manipulation (React native, server side rendering, etc) not applicable to this project I know, but getting a surface level understanding of `useRef, useMemo, useCallback` will be BIG BIG points in a junior React interview

All in all I think this is great work and I just wanted to try to provide some useful feedback for you all to carry into the job hunt and the next chapter of your careers as devs! Please feel free to follow up with any questions on slack and I'd be happy to schedule a time to go over some more things specific to the PR process that I learned on the job post Turing.

**Comment by mr-ryan12** [comment]
Really appreciate the feedback and insight Chris. Can't believe I reached for a `querySelector` to refresh the form. Haven't used it since mod 2 and won't be using it again, at least in React. I was having issues reverting the `<input type="file" />` text back to `No file selected` after file selection and I agree, it was a hacky work around. Thank you for recommending the `useRef` hook. I'll be sure to research the topic. 

I'll be sure to scale down the size of my PR's going forward. I like the single digit file changes rule of thumb. Again, thank you for your input and I'll be sure to make those changes.

**Review by Echory — APPROVED** [review]
Thank you for doing this Ryan, your testing is super thorough!

**Comment by aliroemhildt** [comment]
Thank you so much for the thorough feedback Chris! This is all super helpful info moving forward and all of your points make a lot of sense. 

Ryan - great work on the testing! It's looking really great so far.

**Review by aliroemhildt — APPROVED** [review]

**Review by oacortez — APPROVED** [review]
Thank you for creating this branch, Ryan! I really like how you added fake data to intercept. Everything looks great to me. Glad we got all the test to pass.

**Pull request merged**
